name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test All
        run: go test -v ./...

      - name: Benchmark All
        run: go test ./... -bench=. -benchmem -timeout 5m

      - name: Build WASM
        run: GOOS=js GOARCH=wasm go build -o assets/main.wasm main_js.go

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./assets"

  deploy:
    # Add a dependency to the build job
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
