name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test All
        run: go test -v ./...

      - name: Benchmark ECS
        run: go test ./ecs -bench=.

      - name: Benchmark Game
        run: go test ./game -bench=.
